# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
_libgcc_mutex=0.1=main
_openmp_mutex=5.1=1_gnu
alabaster=0.7.12=pypi_0
anyio=3.6.2=pypi_0
appdirs=1.4.4=pypi_0
argon2-cffi=21.3.0=pypi_0
argon2-cffi-bindings=21.2.0=pypi_0
arrow=1.2.3=pypi_0
asttokens=2.2.1=pypi_0
attrs=22.2.0=pypi_0
babel=2.11.0=pypi_0
backcall=0.2.0=pypi_0
beautifulsoup4=4.11.1=pypi_0
biocommons-seqrepo=0.6.5=pypi_0
bioutils=0.5.7=pypi_0
bleach=5.0.1=pypi_0
bs4=0.0.1=pypi_0
ca-certificates=2022.10.11=h06a4308_0
canonicaljson=1.6.4=pypi_0
certifi=2022.12.7=py39h06a4308_0
cffi=1.15.1=pypi_0
charset-normalizer=2.1.1=pypi_0
coloredlogs=15.0.1=pypi_0
comm=0.1.2=pypi_0
configparser=5.3.0=pypi_0
cssselect=1.2.0=pypi_0
debugpy=1.6.4=pypi_0
decorator=5.1.1=pypi_0
defusedxml=0.7.1=pypi_0
docutils=0.16=pypi_0
entrypoints=0.4=pypi_0
exceptiongroup=1.1.0=pypi_0
executing=1.2.0=pypi_0
fake-useragent=1.1.1=pypi_0
fastjsonschema=2.16.2=pypi_0
fqdn=1.5.1=pypi_0
ga4gh-gks-metaschema=0.2.0rc4=pypi_0
ga4gh-vrs=0.7.7=pypi_0
hgvs=1.5.4=pypi_0
humanfriendly=10.0=pypi_0
idna=3.4=pypi_0
imagesize=1.4.1=pypi_0
importlib-metadata=5.2.0=pypi_0
importlib-resources=5.10.1=pypi_0
inflection=0.5.1=pypi_0
inflector=3.0.1=pypi_0
iniconfig=1.1.1=pypi_0
ipykernel=6.19.4=pypi_0
ipython=8.7.0=pypi_0
ipython-genutils=0.2.0=pypi_0
isoduration=20.11.0=pypi_0
jedi=0.18.2=pypi_0
jinja2=3.1.2=pypi_0
json5=0.9.10=pypi_0
jsonpointer=2.3=pypi_0
jsonschema=3.2.0=pypi_0
jupyter-client=7.4.8=pypi_0
jupyter-core=5.1.1=pypi_0
jupyter-events=0.5.0=pypi_0
jupyter-server=2.0.5=pypi_0
jupyter-server-terminals=0.4.3=pypi_0
jupyterlab-pygments=0.2.2=pypi_0
jupyterlab-server=2.16.6=pypi_0
ld_impl_linux-64=2.38=h1181459_1
libffi=3.3=he6710b0_2
libgcc-ng=11.2.0=h1234567_1
libgomp=11.2.0=h1234567_1
libstdcxx-ng=11.2.0=h1234567_1
lxml=4.9.2=pypi_0
markdown=3.4.1=pypi_0
markupsafe=2.1.1=pypi_0
matplotlib-inline=0.1.6=pypi_0
mistune=2.0.4=pypi_0
nbclassic=0.4.8=pypi_0
nbclient=0.7.2=pypi_0
nbconvert=7.2.7=pypi_0
nbformat=5.7.1=pypi_0
ncurses=6.3=h5eee18b_3
nest-asyncio=1.5.6=pypi_0
notebook-shim=0.2.2=pypi_0
numpy=1.24.1=pypi_0
openssl=1.1.1s=h7f8727e_0
packaging=22.0=pypi_0
pandocfilters=1.5.0=pypi_0
parse=1.19.0=pypi_0
parsley=1.3=pypi_0
parso=0.8.3=pypi_0
pexpect=4.8.0=pypi_0
pickleshare=0.7.5=pypi_0
pip=22.3.1=py39h06a4308_0
platformdirs=2.6.0=pypi_0
pluggy=1.0.0=pypi_0
prometheus-client=0.15.0=pypi_0
prompt-toolkit=3.0.36=pypi_0
psutil=5.9.4=pypi_0
psycopg2=2.9.5=pypi_0
psycopg2-binary=2.9.5=pypi_0
ptyprocess=0.7.0=pypi_0
pure-eval=0.2.2=pypi_0
pycparser=2.21=pypi_0
pyee=8.2.2=pypi_0
pygments=2.13.0=pypi_0
pyppeteer=1.0.2=pypi_0
pyquery=2.0.0=pypi_0
pyrsistent=0.19.2=pypi_0
pysam=0.20.0=pypi_0
pytest=7.2.0=pypi_0
python=3.9.0=hdb3f193_2
python-dateutil=2.8.2=pypi_0
python-json-logger=2.0.4=pypi_0
python-jsonschema-objects=0.4.1=pypi_0
pytz=2022.7=pypi_0
pyyaml=6.0=pypi_0
pyzmq=24.0.1=pypi_0
readline=8.2=h5eee18b_0
requests=2.28.1=pypi_0
requests-html=0.10.0=pypi_0
rfc3339-validator=0.1.4=pypi_0
rfc3986-validator=0.1.1=pypi_0
send2trash=1.8.0=pypi_0
setuptools=65.6.3=pypi_0
simplejson=3.18.0=pypi_0
six=1.16.0=pypi_0
sniffio=1.3.0=pypi_0
snowballstemmer=2.2.0=pypi_0
soupsieve=2.3.2.post1=pypi_0
sphinx=3.5.4=pypi_0
sphinxcontrib-applehelp=1.0.2=pypi_0
sphinxcontrib-devhelp=1.0.2=pypi_0
sphinxcontrib-htmlhelp=2.0.0=pypi_0
sphinxcontrib-jsmath=1.0.1=pypi_0
sphinxcontrib-qthelp=1.0.3=pypi_0
sphinxcontrib-serializinghtml=1.1.5=pypi_0
sqlite=3.40.0=h5082296_0
sqlparse=0.4.3=pypi_0
stack-data=0.6.2=pypi_0
tabulate=0.9.0=pypi_0
terminado=0.17.1=pypi_0
tinycss2=1.2.1=pypi_0
tk=8.6.12=h1ccaba5_0
tomli=2.0.1=pypi_0
tornado=6.2=pypi_0
tqdm=4.64.1=pypi_0
traitlets=5.8.0=pypi_0
tzdata=2022g=h04d1e81_0
uri-template=1.2.0=pypi_0
urllib3=1.26.13=pypi_0
w3lib=2.1.1=pypi_0
wcwidth=0.2.5=pypi_0
webcolors=1.12=pypi_0
webencodings=0.5.1=pypi_0
websocket-client=1.4.2=pypi_0
websockets=10.4=pypi_0
wheel=0.37.1=pyhd3eb1b0_0
xz=5.2.8=h5eee18b_0
yoyo-migrations=8.2.0=pypi_0
zipp=3.11.0=pypi_0
zlib=1.2.13=h5eee18b_0
