name: mybindertest
channels:
  - bioconda
  - r
  - temp
  - defaults
dependencies:
  - ca-certificates=2022.10.11=hecd8cb5_0
  - certifi=2022.12.7=py39hecd8cb5_0
  - libcxx=14.0.6=h9765a3e_0
  - libffi=3.4.2=hecd8cb5_6
  - ncurses=6.3=hca72f7f_3
  - openssl=1.1.1s=hca72f7f_0
  - pip=22.3.1=py39hecd8cb5_0
  - python=3.9.15=h218abb5_2
  - readline=8.2=hca72f7f_0
  - sqlite=3.40.0=h880c91c_0
  - tk=8.6.12=h5d9f67b_0
  - tzdata=2022g=h04d1e81_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.8=h6c40b1e_0
  - zlib=1.2.13=h4dc903c_0
  - pip:
    - biocommons-seqrepo==0.6.5
    - bioutils==0.5.7
    - canonicaljson==1.6.4
    - coloredlogs==15.0.1
    - jsonschema==3.2.0
    - numpy==1.24.0
    - python-jsonschema-objects==0.4.1
    - pyyaml==6.0
    - ga4gh-gks-metaschema==0.2.0rc4
    - ga4gh-vrs==0.7.7
    - hgvs==1.5.4

prefix: /Users/M278428/opt/anaconda3/envs/mybindertest
